#Desafio 04

n = input('Digite algo: ')
print(n.isnumeric())
print(n.isalnum())
print(n.isalpha())
print(n.isdecimal())
print(n.isdigit())
print(n.isidentifier())
print(n.islower())
print(n.isprintable())
print(n.isspace())
print(n.istitle())
print(n.isupper())
print(n.__init_subclass__())
